name: PR
on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

concurrency:
  group: ${{ github.ref }} && ${{ github.workflow }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  check:
    uses: helloextend/gha-reusable-workflows/.github/workflows/package-pr-checks.yml@v13.5.2
    with:
      jestParallelization: 1
    secrets: inherit
